#!/usr/bin/env python
"""Generate a small data/sample/ subset from data/raw/ for offline demos.

Not part of the training/evaluation pipeline -- purely a convenience so the
project can be demonstrated (EDA cells, a few predictions) without needing
the full ~120MB raw dataset loaded, and as a fallback if data/raw/ is ever
unavailable. The real pipeline (run_pipeline.py) always uses data/raw/ and
data/processed/, never data/sample/.

Usage:
    python backend/scripts/make_data_sample.py [--rows 200]
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
RAW_DIR = PROJECT_ROOT / "data" / "raw"
SAMPLE_DIR = PROJECT_ROOT / "data" / "sample"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rows", type=int, default=200, help="Rows to keep per file")
    args = parser.parse_args()

    if not RAW_DIR.is_dir():
        print(f"data/raw/ not found at {RAW_DIR} -- nothing to sample.")
        return 1

    SAMPLE_DIR.mkdir(parents=True, exist_ok=True)
    csv_files = sorted(RAW_DIR.glob("*.csv"))
    if not csv_files:
        print("No CSV files found under data/raw/.")
        return 1

    for path in csv_files:
        df = pd.read_csv(path, nrows=args.rows)
        out_path = SAMPLE_DIR / path.name
        df.to_csv(out_path, index=False)
        print(f"{path.name}: {len(df)} rows -> {out_path.relative_to(PROJECT_ROOT)}")

    readme = SAMPLE_DIR / "README.md"
    readme.write_text(
        "# data/sample/\n\n"
        f"First {args.rows} rows of each raw Olist CSV, generated by "
        "`backend/scripts/make_data_sample.py` for offline demos and quick "
        "EDA checks only. Not used by the training/evaluation pipeline, the "
        "shipped model checkpoints, or the backend API -- those all use "
        "`data/raw/` and `data/processed/` (already present in this delivery). "
        "Row counts and joins are not guaranteed to be referentially complete "
        "across files; regenerate with:\n\n"
        "```\npython backend/scripts/make_data_sample.py --rows 200\n```\n",
        encoding="utf-8",
    )
    print(f"Wrote {readme.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
