#!/usr/bin/env python
"""Regenerates results/reproduced_metrics.json and results/fair_model_comparison.json
from whatever checkpoints are CURRENTLY on disk -- the single source of truth
for "what do the published numbers say", replacing the ad-hoc process that
previously let these files go stale after a retraining run silently
overwrote models/bert_review_sentiment/ without updating them (see
Technical Review #03).

Every write is stamped with checkpoint_fingerprint() so a future staleness
check (app/main.py's lifespan) can detect the same failure mode again
instead of silently serving wrong numbers.

Usage:
    cd backend && python scripts/regenerate_metrics.py
"""
from __future__ import annotations

import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_DIR))
PROJECT_ROOT = BACKEND_DIR.parent

import pandas as pd  # noqa: E402

from app.ml import preprocessing as prep  # noqa: E402
from app.ml.utils import checkpoint_fingerprint, write_json  # noqa: E402
from app.core.config import settings  # noqa: E402
from scripts.evaluate import evaluate_bert, evaluate_cnn2d  # noqa: E402


def main() -> None:
    manifest = prep.load_split_manifest(PROJECT_ROOT / "artifacts" / "split_manifest.json")
    print(f"Loaded split manifest (seed={manifest['seed']}, sizes={manifest['sizes']})")

    reviews = pd.read_csv(PROJECT_ROOT / "data" / "interim" / "reviews_translated.csv")
    sent_df = prep.build_sentiment_dataframe(reviews)

    bert_path = settings.BERT_MODEL_PATH
    cnn_checkpoint = settings.CNN_CHECKPOINT_PATH
    cnn_tokenizer = settings.CNN_TOKENIZER_PATH

    print("\n=== BERT ===")
    bert_results = evaluate_bert(bert_path, manifest, sent_df)
    bert_fp = checkpoint_fingerprint(bert_path)
    print(f"BERT checkpoint fingerprint: {bert_fp}")

    print("\n=== CNN2D ===")
    cnn_results = evaluate_cnn2d(cnn_checkpoint, cnn_tokenizer, manifest, sent_df)
    # CNN2D ships as a single .pt file, not a directory of *.safetensors --
    # fingerprint the file itself directly rather than the directory-glob
    # helper meant for HF-style checkpoints.
    import hashlib
    cnn_fp = hashlib.sha256(cnn_checkpoint.read_bytes()).hexdigest()[:16]
    print(f"CNN2D checkpoint fingerprint: {cnn_fp}")

    reproduced = {
        "methodology": (
            "Both models evaluated via genuine forward-pass inference (no retraining) "
            "using their saved checkpoints on a corrected, deduplicated, leakage-free "
            "70/10/20 split (see DATA_LEAKAGE_AUDIT.md and artifacts/split_manifest.json). "
            "Regenerated by scripts/regenerate_metrics.py -- run this after ANY retraining "
            "that changes either checkpoint, never hand-edit these numbers."
        ),
        "seed": manifest["seed"],
        "split_sizes": manifest["sizes"],
        "bert": {**bert_results, "checkpoint_sha256": bert_fp},
        "cnn2d": {**cnn_results, "checkpoint_sha256": cnn_fp},
    }
    write_json(PROJECT_ROOT / "results" / "reproduced_metrics.json", reproduced)
    print("\nWrote results/reproduced_metrics.json")

    bert_test = bert_results["test"]["metrics"]
    cnn_test = cnn_results["test"]["metrics"]
    fair = {
        "methodology": "Both models evaluated on the IDENTICAL corrected test split (same review_ids, same seed, same label mapping).",
        "test_size": manifest["sizes"]["test"],
        "bert_test_metrics": bert_test,
        "cnn2d_test_metrics": cnn_test,
        "bert_checkpoint_sha256": bert_fp,
        "cnn2d_checkpoint_sha256": cnn_fp,
        # Computed from the metrics just measured, never hand-typed -- the
        # exact bug in Technical Review #03 was this conclusion silently
        # going stale relative to the numbers next to it.
        "better_by_accuracy": "bert" if bert_test["accuracy"] >= cnn_test["accuracy"] else "cnn2d",
        "better_by_f1_macro": "bert" if bert_test["f1_macro"] >= cnn_test["f1_macro"] else "cnn2d",
        "better_by_roc_auc": "bert" if bert_test["roc_auc"] >= cnn_test["roc_auc"] else "cnn2d",
    }
    write_json(PROJECT_ROOT / "results" / "fair_model_comparison.json", fair)
    print("Wrote results/fair_model_comparison.json")

    print(f"\nbetter_by_accuracy={fair['better_by_accuracy']}  better_by_f1_macro={fair['better_by_f1_macro']}  better_by_roc_auc={fair['better_by_roc_auc']}")


if __name__ == "__main__":
    main()
