import { GlassCard } from "../ui/GlassCard";
import { SectionHeader } from "../ui/SectionHeader";
import { StatusPill } from "../ui/Badge";
import { RULE_BASED_RECOMMENDATION } from "./demoData";

export function RecommendationsSection() {
  return (
    <section className="bsr-lp-section bsr-lp-section--story">
      <div className="bsr-lp-container">
        <div className="bsr-lp-story-rail bsr-lp-story-rail--last">
          <span className="bsr-lp-story-rail__line" aria-hidden="true" />
          <span className="bsr-lp-story-rail__node bsr-lp-story-rail__node--gold bsr-mono" aria-hidden="true">3</span>

          <div className="bsr-lp-recommendation-split">
            <div className="bsr-lp-recommendation-split__intro">
              <SectionHeader eyebrow="Actionable recommendations" title="Rules over the data, not a language model guessing" description="Baseera's recommendations today are triggered by simple, inspectable thresholds over the same sentiment and trend data shown above." />
              <p className="bsr-caption">
                Not generated by a language model. No recommendation engine is connected to live data yet -- this illustrates the intended
                rule-based approach.
              </p>
            </div>

            <GlassCard glow="gold" className="bsr-lp-recommendation-card">
              <StatusPill tone="gold" dot={false}>Rule-based demonstration recommendation</StatusPill>
              <p className="bsr-h4" style={{ marginTop: "var(--bsr-space-3)" }}>{RULE_BASED_RECOMMENDATION.text}</p>
              <p className="bsr-sm bsr-lp-recommendation-card__basis">{RULE_BASED_RECOMMENDATION.basis}</p>
            </GlassCard>
          </div>
        </div>
      </div>
    </section>
  );
}
