"""create sentiment and batch upload tables

Revision ID: 36ffaba3b9b4
Revises: 
Create Date: 2026-08-17 13:38:45.952138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ffaba3b9b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_upload_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=16), nullable=False),
    sa.Column('text_column_used', sa.String(length=128), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('n_positive', sa.Integer(), nullable=False),
    sa.Column('n_negative', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_upload_jobs_created_at'), 'batch_upload_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_batch_upload_jobs_expires_at'), 'batch_upload_jobs', ['expires_at'], unique=False)
    op.create_table('sentiment_analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('probability_positive', sa.Float(), nullable=False),
    sa.Column('probability_negative', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=16), nullable=False),
    sa.Column('source_language', sa.String(length=8), nullable=False),
    sa.Column('translated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['sentiment_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_feedback_analysis_id'), 'prediction_feedback', ['analysis_id'], unique=False)
    op.create_table('sentiment_analysis_aspects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('aspect', sa.String(length=64), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['sentiment_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_analysis_aspects_analysis_id'), 'sentiment_analysis_aspects', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_analysis_aspects_analysis_id'), table_name='sentiment_analysis_aspects')
    op.drop_table('sentiment_analysis_aspects')
    op.drop_index(op.f('ix_prediction_feedback_analysis_id'), table_name='prediction_feedback')
    op.drop_table('prediction_feedback')
    op.drop_table('sentiment_analyses')
    op.drop_index(op.f('ix_batch_upload_jobs_expires_at'), table_name='batch_upload_jobs')
    op.drop_index(op.f('ix_batch_upload_jobs_created_at'), table_name='batch_upload_jobs')
    op.drop_table('batch_upload_jobs')
    # ### end Alembic commands ###
