"""create marketplace tables

Revision ID: b590246793c8
Revises: b1c8891786a0
Create Date: 2026-08-24 16:10:37.791744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b590246793c8'
down_revision: Union[str, Sequence[str], None] = 'b1c8891786a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_import_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('update_mode', sa.String(length=16), nullable=True),
    sa.Column('mapping_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grain_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('staged_file_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_sessions_status', 'marketplace_import_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_marketplace_import_sessions_created_at'), 'marketplace_import_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_import_sessions_expires_at'), 'marketplace_import_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_marketplace_import_sessions_file_hash'), 'marketplace_import_sessions', ['file_hash'], unique=False)
    op.create_table('marketplace_dataset_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_session_id', sa.String(length=32), nullable=True),
    sa.Column('parent_version_id', sa.String(length=32), nullable=True),
    sa.Column('update_mode', sa.String(length=16), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('distinct_order_count', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['parent_version_id'], ['marketplace_dataset_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['marketplace_import_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_dataset_versions_created_at'), 'marketplace_dataset_versions', ['created_at'], unique=False)
    op.create_index('ux_marketplace_one_active_version', 'marketplace_dataset_versions', ['is_active'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('marketplace_canonical_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_version_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('order_purchase_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_delivered_customer_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_status', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('customer_unique_id', sa.String(length=64), nullable=False),
    sa.Column('customer_city', sa.String(length=128), nullable=True),
    sa.Column('customer_state', sa.String(length=8), nullable=True),
    sa.Column('payment_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('main_payment_type', sa.String(length=32), nullable=True),
    sa.Column('payment_installments', sa.Integer(), nullable=True),
    sa.Column('review_score', sa.SmallInteger(), nullable=True),
    sa.Column('review_comment_message', sa.Text(), nullable=True),
    sa.Column('seller_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('product_category_name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('freight_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('seller_city', sa.String(length=128), nullable=True),
    sa.Column('seller_state', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['marketplace_dataset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canonical_version_order', 'marketplace_canonical_rows', ['dataset_version_id', 'order_id'], unique=False)
    op.create_index('ix_canonical_version_product', 'marketplace_canonical_rows', ['dataset_version_id', 'product_id'], unique=False, postgresql_where=sa.text('product_id IS NOT NULL'))
    op.create_index('ix_canonical_version_seller', 'marketplace_canonical_rows', ['dataset_version_id', 'seller_id'], unique=False, postgresql_where=sa.text('seller_id IS NOT NULL'))
    op.create_index('ux_canonical_item_key', 'marketplace_canonical_rows', ['dataset_version_id', 'order_id', 'order_item_id'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('marketplace_customer_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_version_id', sa.String(length=32), nullable=False),
    sa.Column('customer_unique_id', sa.String(length=64), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('average_order_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('first_order_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recency', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('monetary', sa.Float(), nullable=True),
    sa.Column('rfm_segment', sa.String(length=64), nullable=True),
    sa.Column('rfm_out_of_distribution', sa.Boolean(), nullable=True),
    sa.Column('customer_city', sa.String(length=128), nullable=True),
    sa.Column('customer_state', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['marketplace_dataset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'customer_unique_id', name='ux_customer_analytics_key')
    )
    op.create_index('ix_customer_analytics_version_segment', 'marketplace_customer_analytics', ['dataset_version_id', 'rfm_segment'], unique=False)
    op.create_index('ix_customer_analytics_version_spend', 'marketplace_customer_analytics', ['dataset_version_id', 'total_spend'], unique=False)
    op.create_table('marketplace_derived_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_version_id', sa.String(length=32), nullable=False),
    sa.Column('artifact_name', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['marketplace_dataset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'artifact_name', name='ux_one_artifact_per_version')
    )
    op.create_table('marketplace_import_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('version_id', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['marketplace_import_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['marketplace_dataset_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_import_audit_created_at'), 'marketplace_import_audit', ['created_at'], unique=False)
    op.create_table('marketplace_product_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_version_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('product_category_name', sa.String(length=128), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('item_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('average_item_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('freight_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('associated_single_category_order_review_average', sa.Float(), nullable=True),
    sa.Column('associated_review_order_count', sa.Integer(), nullable=False),
    sa.Column('associated_review_excluded_order_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['marketplace_dataset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'product_id', name='ux_product_analytics_key')
    )
    op.create_index('ix_product_analytics_version_category', 'marketplace_product_analytics', ['dataset_version_id', 'product_category_name'], unique=False)
    op.create_index('ix_product_analytics_version_revenue', 'marketplace_product_analytics', ['dataset_version_id', 'item_revenue'], unique=False)
    op.create_table('marketplace_seller_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_version_id', sa.String(length=32), nullable=False),
    sa.Column('seller_id', sa.String(length=64), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('item_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('average_item_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('late_delivery_rate', sa.Float(), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('category_count', sa.Integer(), nullable=False),
    sa.Column('seller_city', sa.String(length=128), nullable=True),
    sa.Column('seller_state', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['marketplace_dataset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'seller_id', name='ux_seller_analytics_key')
    )
    op.create_index('ix_seller_analytics_version_late', 'marketplace_seller_analytics', ['dataset_version_id', 'late_delivery_rate'], unique=False)
    op.create_index('ix_seller_analytics_version_revenue', 'marketplace_seller_analytics', ['dataset_version_id', 'item_revenue'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seller_analytics_version_revenue', table_name='marketplace_seller_analytics')
    op.drop_index('ix_seller_analytics_version_late', table_name='marketplace_seller_analytics')
    op.drop_table('marketplace_seller_analytics')
    op.drop_index('ix_product_analytics_version_revenue', table_name='marketplace_product_analytics')
    op.drop_index('ix_product_analytics_version_category', table_name='marketplace_product_analytics')
    op.drop_table('marketplace_product_analytics')
    op.drop_index(op.f('ix_marketplace_import_audit_created_at'), table_name='marketplace_import_audit')
    op.drop_table('marketplace_import_audit')
    op.drop_table('marketplace_derived_artifacts')
    op.drop_index('ix_customer_analytics_version_spend', table_name='marketplace_customer_analytics')
    op.drop_index('ix_customer_analytics_version_segment', table_name='marketplace_customer_analytics')
    op.drop_table('marketplace_customer_analytics')
    op.drop_index('ux_canonical_item_key', table_name='marketplace_canonical_rows', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_canonical_version_seller', table_name='marketplace_canonical_rows', postgresql_where=sa.text('seller_id IS NOT NULL'))
    op.drop_index('ix_canonical_version_product', table_name='marketplace_canonical_rows', postgresql_where=sa.text('product_id IS NOT NULL'))
    op.drop_index('ix_canonical_version_order', table_name='marketplace_canonical_rows')
    op.drop_table('marketplace_canonical_rows')
    op.drop_index('ux_marketplace_one_active_version', table_name='marketplace_dataset_versions', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_marketplace_dataset_versions_created_at'), table_name='marketplace_dataset_versions')
    op.drop_table('marketplace_dataset_versions')
    op.drop_index(op.f('ix_marketplace_import_sessions_file_hash'), table_name='marketplace_import_sessions')
    op.drop_index(op.f('ix_marketplace_import_sessions_expires_at'), table_name='marketplace_import_sessions')
    op.drop_index(op.f('ix_marketplace_import_sessions_created_at'), table_name='marketplace_import_sessions')
    op.drop_index('ix_import_sessions_status', table_name='marketplace_import_sessions')
    op.drop_table('marketplace_import_sessions')
    # ### end Alembic commands ###
